### ISSUE TITLE
react-native-volume-manager' doesn't seem to be linked

### ISSUE THREAD

**Issue by Bravo-Lin** [hirbod/react-native-volume-manager#1]
After I installed this module, I had this problem after starting the project。

I have tried restarting project and run ` ./gradlew clean`

![image](https://user-images.githubusercontent.com/43205138/174512621-c01cda69-15c4-4b11-a6b5-78556306e4f1.png)

**Comment by hirbod** [comment]
Thanks for reporting, I'll investigate

**Comment by hirbod** [comment]
This issue has been fixed, thanks to @barthap
Will release 0.4.1

**Comment by hirbod** [comment]
New version with the fix has been released
