### ISSUE TITLE
Upgrade kotlin version for react-native-volume-manager to support kotlin-android-extensions plugin 1.6.20

### ISSUE THREAD

**Issue by MartsTech** [hirbod/react-native-volume-manager#11]
### Description
The Android Gradle plugin requires kotlin-android-extensions Gradle plugin version 1.6.20 or higher. However, the current version of the react-native-volume-manager dependency is using org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10, which does not satisfy the required version. As a result, building the project fails with the following error message: 

`The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher. The following dependencies do not satisfy the required version: project ':react-native-volume-manager' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10`.

### Solution:
To resolve this issue, we need to upgrade the kotlin version to 1.6.20 or higher in the react-native-volume-manager dependency. This can be achieved by updating the version number of the kotlin-gradle-plugin in the build.gradle file of the react-native-volume-manager module to 1.6.20 or higher.

**Comment by hirbod** [comment]
Thanks for raising this. I'll take care this weekend. This will most likely target RN 0.71+ only though, so I'll make a breaking change release.

**Comment by MartsTech** [comment]
Hi @hirbod, just checking in to see if there has been any progress on upgrading the kotlin version for react-native-volume-manager. Thank you for looking into this issue!

**Comment by hirbod** [comment]
Sorry @MartsTech I was caught up and will be back after easter. Will tackle this after.

**Comment by hirbod** [comment]
Hi @MartsTech, I started working on it. Expect a release soon!

**Comment by pratik-yadav-cvent** [comment]
Hi @hirbod, Is there any ETA for this fix?

**Comment by hirbod** [comment]
New release is ready in ~1 hour

**Comment by hirbod** [comment]
Version 1.3.0 has been released. This issue is resolved now.
