### ISSUE TITLE
Android: isRingerListenerEnabled() is returning silent mode status, not the ringer listener status

### ISSUE THREAD

**Issue by harriha** [hirbod/react-native-volume-manager#24]
Hi,

And thanks for the library, highly useful!

From the docs:

> `isRingerListenerEnabled(): Promise<boolean>`: Asynchronously checks whether a ringer mode listener is enabled.

I might be misinterpreting things here, but I think there's some confusion here. This method seems to return whether the device is set to silent or not, but the docs and name suggest that this would tell whether a ringer listener is enabled or not. Also, to me, the "silent status" and "silent listener status" are a bit mixed up in the [codebase](https://github.com/hirbod/react-native-volume-manager/blob/main/android/src/main/java/com/reactnativevolumemanager/Utils.kt#L26). Does this observation make sense or is it just me getting confused for no good reason?

I've been having some struggle with the event listener handling, as e.g. the volume listener and ringer mode listener are working differently, but I guess there's a valid reason for the ringer mode listener to be setup differently than the others. Anyway, considering the current way of how the ringer mode listening is happening, having a way to check whether ringer mode listener is enabled would be useful.

**Comment by hirbod** [comment]
Hi @harriha, thanks for filing this issue, and sorry for the long delay. This was indeed a bug/documentation issue on my end. The method has been renamed to `isAndroidDeviceSilent`.

It asynchronously checks if the device is in a silent state, including silent mode, vibrate mode, muted volume, or Do Not Disturb mode. With all the listeners and other functions available, I believe every scenario is covered now.
