### ISSUE TITLE
Volume manger is not working in the background mode

### ISSUE THREAD

**Issue by rajdivergenceneuro** [hirbod/react-native-volume-manager#33]
Related issue(Android)

Step to produce

- Add the volume manage in background listener (React-Native-Ble-Manager, React-Native-Background-Timer).
- I'm not able to change the volume in background mode
- Issue is only detected in oxygen OS

Using oxygen OS - 13.1

I attached screen shot for the reference. Given permission is already granted.

![Screenshot 2024-03-04 at 5 24 41 PM](https://github.com/hirbod/react-native-volume-manager/assets/159823886/3778584b-f2e3-473d-91db-373e032b52ff)

**Comment by hirbod** [comment]
Please provide a Repro. Also I am not aware of Oxygen OS

**Comment by rajdivergenceneuro** [comment]
> Please provide a Repro. Also I am not aware of Oxygen OS

- It is available in OnePlus device(Oxygen OS). 
- In react native, register listener that support background activity and add the setVolume inside it.
- when user add their app in background system setting is not changing

**Comment by hirbod** [comment]
Please create a minimal repo for me if you want me to investigate here. I'll reopen the issue afterwards
