### ISSUE TITLE
Ability to use this while the app is unfocused or the screen is off

### ISSUE THREAD

**Issue by kross-italk** [hirbod/react-native-volume-manager#36]
Hello, great library. It was very easy to get up and running with this in a new react-native project. 

Does this library support accessing volume events while the App activity is unfocused (in another app, on the home screen) or when the screen is off entirely? 

I want to get an event about volume button *presses* (Not volume changes, so android.media.VOLUME_CHANGED seems inappropriate as the base Intent). If this project isn't correct, can anyone point me in the right direction?

**Comment by hirbod** [comment]
I don't think that this is possible under normal circumstances, and also out of scope for this library.
Android imposes restrictions on background apps to conserve battery and system resources. This includes limiting their ability to receive hardware key events like volume button presses.

If your app is playing media in the background (e.g., music player), it can indirectly respond to volume changes. The system will adjust the media volume, and your app might be able to listen to it even when backgrounded, but I don't know if you can run code or if you encounter limitations. Accessibility Service can potentially intercept global key events, but I don't have any experience.
