### ISSUE TITLE
iOS: addVolumeListener is not working on physical device iOS 17

### ISSUE THREAD

**Issue by Vijaykumarj** [hirbod/react-native-volume-manager#39]
Hi 

I’m attempting to use this package to capture a photo when the volume keys are pressed, but it isn’t working as expected on a physical device. It functions correctly on all versions of Android emulators, however.

Steps to reproduce the issue:
1. Clone the repository.
2. Install the node modules and run `pod install` in the `examples` folder.
3. Add a console log in the `addVolumeListener` event at line 50 in the `react-native-volume-manager/example/App.tsx` file.
4. Run the app on a physical device.
5. No logs appear in the Metro console, and the volume UI continues to display even when the toast is turned off.

Thank you in advance.

**Comment by hirbod** [comment]
I refactored a lot of code for iOS and might have just fixed it, as it works fine on physical devices from iOS 16 to 18.2 for me.
Please make sure to upgrade to v2, which I am releasing in the next 30 minutes
