### ISSUE TITLE
[error] esa bug build expo dev clien 

### ISSUE THREAD

**Issue by mathcovax** [hirbod/react-native-volume-manager#4]
I import the package and launch build dev version with : `eas build --profile development --platform android`

I obtain this error on "run gradlew" step : https://hastebin.com/ejiditukuj.sql

**Comment by hirbod** [comment]
Looks like there is a mismatch with the Kotlin version in your setup.

**Comment by mathcovax** [comment]
> 

do you have a solution ? change react version or expo cli ?

**Comment by mathcovax** [comment]
I solve the problem by changing kotlin_version in build.gradle :
`def kotlin_version = rootProject.ext.has('kotlinVersion') ? rootProject.ext.get('kotlinVersion') : project.properties['VolumeManager_kotlinVersion']`
to 
`def kotlin_version = "1.6.10"`

**Comment by hirbod** [comment]
Thanks for pointing out @matechcide, new update coming soon with a fix
