### ISSUE TITLE
With modal(react-native)VolumeManager.showNativeVolumeUI({ enabled: false})  doesn't work 

### ISSUE THREAD

**Issue by kajalverma98** [hirbod/react-native-volume-manager#40]
Hi, 
when component is using modal to show camera, VolumeManager.showNativeVolumeUI({ enabled: false}) doesn't work, and volume button is still visible (Both Android and IOS).
Thanks.

**Comment by RiteshJariwala** [comment]
Yeah, i am facing same problem if modal window open then it still display volume toast ui, anyone has solution?

**Comment by hirbod** [comment]
I guess the Camera changes the AudioSession, causing the library to lose the listener. Try resetting the audio category or session using the available methods, but I can't guarantee it will work with an active camera.

**Comment by hirbod** [comment]
Please test 2.0.5 and report back if it works. I believe Android should work, not sure about iOS yet
