### ISSUE TITLE
Bug: VolumeManager.showNativeVolumeUI({ enabled: false}) does not work with webview

### ISSUE THREAD

**Issue by youtipie** [hirbod/react-native-volume-manager#41]
As said in the capture, VolumeManager.showNativeVolumeUI({enabled: false}) does not work with webview. UI is hidden for a moment when user is not interacting with webview. When the user interacts with the webview, the UI goes back to enabled.

**Comment by hirbod** [comment]
The webview overwrites the audio session; I don't think there is much I can do, sorry.
