### ISSUE TITLE
Calling `getVolume` causes a crash on iOS on new architecture, React Native 0.76

### ISSUE THREAD

**Issue by hrastnik** [hirbod/react-native-volume-manager#43]
Calling `getVolume` causes a crash on iOS with the following error observed in XCode logs:

```
AVAudioSession_iOS.mm:2386  Failed to set category, error: -50
```

Steps to reproduce:

1. Initialize a new React Native v0.76 project
2. Install react-native-volume-manager
3. Run `getVolume`

The app crashes.

The following snippet is enough to confirm it crashes when calling getVolume

```
import React from 'react';
import {Button, View} from 'react-native';
import {getVolume} from 'react-native-volume-manager';

export default function App() {
  return (
    <View style={{flex: 1, justifyContent: 'center'}}>
      <Button
        title="Get volume"
        onPress={async () => {
          const volume = await getVolume();
          console.log('Volume:', volume);
        }}></Button>
    </View>
  );
}
```

**Comment by hirbod** [comment]
This library is not compatible with the new arch yet.

**Comment by hrastnik** [comment]
@hirbod Are you planning to add support for the new architecture soon?

**Comment by hirbod** [comment]
I am planning since 2022, but no-one stepped in so far to help, I don't have any knowledge. I have hopes that expo-audio might deprecate my library soon though.

**Comment by marcosinigaglia** [comment]
Hi @hirbod , we are finishing to migrate our ble library with RN 0.76 (https://github.com/innoveit/react-native-ble-manager/pull/1285), you can take a look in the changes to support this lib. I can help if you have problems.

**Comment by hrastnik** [comment]
@hirbod I'd be happy to help. And for the last few days I've been trying to get the library to work with the new architecture while remaining backwards compatible.

So far I have a solution for iOS, but it's kind of complex when I try to keep it backward compatible. Would you be ok with having a breaking change and forcing RN76 users to use the new library version and <RN76 users would stay on the current version?

**Comment by hirbod** [comment]
@hrastnik absolutely. I was planning to make a final release for <RN76 to fix the Android crash and going forward, we can force v2 for RN76+

**Comment by d-moreira** [comment]
hey @hirbod any news regarding new arch support and RN0.76?

**Comment by hirbod** [comment]
I refactored a lot of code and made everything more robust. v2 will be released in ~30 minutes
